# Generated by Django 5.0.6 on 2026-06-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='kind',
            field=models.CharField(choices=[('income', 'Поступление'), ('expense', 'Расход')], default='income', help_text='Определяет смысловое направление типа для аналитики.', max_length=10, verbose_name='Направление'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'transaction_type'), name='unique_category_per_type'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_subcategory_per_category'),
        ),
    ]
